const LANG_EN_FANTASKICAL = {
    TASKS: "Tasks",
    CALENDAR: "Calendar",
    ACTIVE: "Active",
    COMPLETED: "Completed",
    ADD_TASK_PLACEHOLDER: "Add task",
    ADD_EVENT_PLACEHOLDER: "Add event",
    ADD_EVENT_MODAL_TITLE: "Add New Event",
    EVENT_TITLE_LABEL: "Event Title",
    EVENT_DATE_LABEL: "Date",
    START_TIME_LABEL: "Start Time",
    END_TIME_LABEL: "End Time",
    DESCRIPTION_LABEL: "Description",
    SAVE_EVENT_BTN: "Save Event",
    EVENT_DETAILS_TITLE: "Event Details",
    ALL_DAY: "All Day",
    NO_DESCRIPTION: "No description provided.",
    CLOSE_BTN: "Close",
    NO_UPCOMING_EVENTS: "No upcoming events",
    NO_TASKS: "No tasks here. Add one to get started!",
    NOTIFICATION_TITLE: "Event: {title}",
    NOTIFICATION_BODY_TIME: "Starts at {time}",
    NOTIFICATION_BODY_ALLDAY: "All day",
    NOTIFICATION_VIEW_DETAILS: "View Details"
};

const LANG_JP_FANTASKICAL = {
    TASKS: "タスク",
    CALENDAR: "カレンダー",
    ACTIVE: "アクティブ",
    COMPLETED: "完了済み",
    ADD_TASK_PLACEHOLDER: "タスクを追加",
    ADD_EVENT_PLACEHOLDER: "イベントを追加",
    ADD_EVENT_MODAL_TITLE: "新しいイベントを追加",
    EVENT_TITLE_LABEL: "イベントのタイトル",
    EVENT_DATE_LABEL: "日付",
    START_TIME_LABEL: "開始時刻",
    END_TIME_LABEL: "終了時刻",
    DESCRIPTION_LABEL: "説明",
    SAVE_EVENT_BTN: "イベントを保存",
    EVENT_DETAILS_TITLE: "イベント詳細",
    ALL_DAY: "終日",
    NO_DESCRIPTION: "説明はありません。",
    CLOSE_BTN: "閉じる",
    NO_UPCOMING_EVENTS: "今後のイベントはありません",
    NO_TASKS: "ここにタスクはありません。追加して始めましょう！",
    NOTIFICATION_TITLE: "イベント：{title}",
    NOTIFICATION_BODY_TIME: "{time}に開始",
    NOTIFICATION_BODY_ALLDAY: "終日",
    NOTIFICATION_VIEW_DETAILS: "詳細を見る"
};

const LANG_DE_FANTASKICAL = {
    TASKS: "Aufgaben",
    CALENDAR: "Kalender",
    ACTIVE: "Aktiv",
    COMPLETED: "Abgeschlossen",
    ADD_TASK_PLACEHOLDER: "Aufgabe hinzufügen",
    ADD_EVENT_PLACEHOLDER: "Ereignis hinzufügen",
    ADD_EVENT_MODAL_TITLE: "Neues Ereignis hinzufügen",
    EVENT_TITLE_LABEL: "Ereignistitel",
    EVENT_DATE_LABEL: "Datum",
    START_TIME_LABEL: "Startzeit",
    END_TIME_LABEL: "Endzeit",
    DESCRIPTION_LABEL: "Beschreibung",
    SAVE_EVENT_BTN: "Ereignis speichern",
    EVENT_DETAILS_TITLE: "Ereignisdetails",
    ALL_DAY: "Ganztägig",
    NO_DESCRIPTION: "Keine Beschreibung angegeben.",
    CLOSE_BTN: "Schließen",
    NO_UPCOMING_EVENTS: "Keine bevorstehenden Ereignisse",
    NO_TASKS: "Hier sind keine Aufgaben. Fügen Sie eine hinzu, um loszulegen!",
    NOTIFICATION_TITLE: "Ereignis: {title}",
    NOTIFICATION_BODY_TIME: "Beginnt um {time}",
    NOTIFICATION_BODY_ALLDAY: "Ganztägig",
    NOTIFICATION_VIEW_DETAILS: "Details anzeigen"
};

const LANG_ES_FANTASKICAL = {
    TASKS: "Tareas",
    CALENDAR: "Calendario",
    ACTIVE: "Activas",
    COMPLETED: "Completadas",
    ADD_TASK_PLACEHOLDER: "Añadir tarea",
    ADD_EVENT_PLACEHOLDER: "Añadir evento",
    ADD_EVENT_MODAL_TITLE: "Añadir nuevo evento",
    EVENT_TITLE_LABEL: "Título del evento",
    EVENT_DATE_LABEL: "Fecha",
    START_TIME_LABEL: "Hora de inicio",
    END_TIME_LABEL: "Hora de finalización",
    DESCRIPTION_LABEL: "Descripción",
    SAVE_EVENT_BTN: "Guardar evento",
    EVENT_DETAILS_TITLE: "Detalles del evento",
    ALL_DAY: "Todo el día",
    NO_DESCRIPTION: "No se proporcionó descripción.",
    CLOSE_BTN: "Cerrar",
    NO_UPCOMING_EVENTS: "No hay eventos próximos",
    NO_TASKS: "No hay tareas aquí. ¡Añade una para empezar!",
    NOTIFICATION_TITLE: "Evento: {title}",
    NOTIFICATION_BODY_TIME: "Empieza a las {time}",
    NOTIFICATION_BODY_ALLDAY: "Todo el día",
    NOTIFICATION_VIEW_DETAILS: "Ver detalles"
};

const LANG_KO_FANTASKICAL = {
    TASKS: "작업",
    CALENDAR: "캘린더",
    ACTIVE: "활성",
    COMPLETED: "완료됨",
    ADD_TASK_PLACEHOLDER: "작업 추가",
    ADD_EVENT_PLACEHOLDER: "이벤트 추가",
    ADD_EVENT_MODAL_TITLE: "새 이벤트 추가",
    EVENT_TITLE_LABEL: "이벤트 제목",
    EVENT_DATE_LABEL: "날짜",
    START_TIME_LABEL: "시작 시간",
    END_TIME_LABEL: "종료 시간",
    DESCRIPTION_LABEL: "설명",
    SAVE_EVENT_BTN: "이벤트 저장",
    EVENT_DETAILS_TITLE: "이벤트 상세 정보",
    ALL_DAY: "하루 종일",
    NO_DESCRIPTION: "설명이 제공되지 않았습니다.",
    CLOSE_BTN: "닫기",
    NO_UPCOMING_EVENTS: "예정된 이벤트 없음",
    NO_TASKS: "여기에 작업이 없습니다. 시작하려면 하나 추가하세요!",
    NOTIFICATION_TITLE: "이벤트: {title}",
    NOTIFICATION_BODY_TIME: "{time}에 시작",
    NOTIFICATION_BODY_ALLDAY: "하루 종일",
    NOTIFICATION_VIEW_DETAILS: "세부 정보 보기"
};

const LANG_ZH_FANTASKICAL = {
    TASKS: "任务",
    CALENDAR: "日历",
    ACTIVE: "进行中",
    COMPLETED: "已完成",
    ADD_TASK_PLACEHOLDER: "添加任务",
    ADD_EVENT_PLACEHOLDER: "添加事件",
    ADD_EVENT_MODAL_TITLE: "添加新事件",
    EVENT_TITLE_LABEL: "事件标题",
    EVENT_DATE_LABEL: "日期",
    START_TIME_LABEL: "开始时间",
    END_TIME_LABEL: "结束时间",
    DESCRIPTION_LABEL: "描述",
    SAVE_EVENT_BTN: "保存事件",
    EVENT_DETAILS_TITLE: "事件详情",
    ALL_DAY: "全天",
    NO_DESCRIPTION: "未提供描述。",
    CLOSE_BTN: "关闭",
    NO_UPCOMING_EVENTS: "没有即将到来的事件",
    NO_TASKS: "这里没有任务。添加一个以开始！",
    NOTIFICATION_TITLE: "事件：{title}",
    NOTIFICATION_BODY_TIME: "开始于 {time}",
    NOTIFICATION_BODY_ALLDAY: "全天",
    NOTIFICATION_VIEW_DETAILS: "查看详情"
};
